--scoremanage 테이블 생성
DROP TABLE GAME_MANAGE;
create table GAME_MANAGE(
 GAME_ID number primary key --게임_ID
 ,GAME_NM varchar2(300) not null --게임_명
 ,GAME_CONT varchar2(4000) not null --게임_내용
 ,GAME_DTIME varchar2(14) not null --게임_일시
 ,GAME_GB_CD varchar2(2) not null --게임_구분_코드(01:정기전,02:교류전)
 ,CLUB_ID number --클럽_ID
 ,WRIGHTER_ID VARCHAR2(100)
 ,WRIGHTER_NM VARCHAR2(100)
 ,WRIGHT_DATE DATE --등록_일자
 ,UPDATE_DATE DATE --수정_일자
);

ALTER TABLE GAME_MEMBER MODIFY COLUMN (MEM_ID varchar2(100));

create sequence GAME_ID_SEQ
start with 1 --1부터 시작
increment by 1 --1씩 증가옵션
nocache;
select GAME_ID_SEQ.nextval from dual;

DROP TABLE GAME_MEMBER;
create table GAME_MEMBER(
  GAME_MEM_ID NUMBER --게임_회원_ID
 ,GAME_ID     number --게임_ID
 ,MEM_ID      varchar2(100) --회원_ID
 ,MEM_NAME    varchar2(50)      
 ,WRIGHT_DATE DATE --등록_일자
 ,GAME_TEAM   VARCHAR(10) --게임_팀
);
ALTER TABLE GAME_MEMBER
ADD CONSTRAINT PK_GAME_MEMBER PRIMARY KEY(GAME_MEM_ID);

create sequence GAME_MEM_ID_SEQ
start with 1 --1부터 시작
increment by 1 --1씩 증가옵션
nocache;

select GAME_MEM_ID_SEQ.nextval from dual;

DROP TABLE SCORE_MANAGE;
create table SCORE_MANAGE(
  SCORE_ID   number --점수_ID
 ,GAME_ID    number --게임_ID
 ,GAME_DTIME varchar2(14) --게임_일시
 ,MEM_ID     varchar2(100) --회원_ID
 ,MEM_NAME     varchar2(50) --회원_NM
 ,TEAM_NM    varchar2(50) --팀_NM
 ,GAME_SEQ   NUMBER --게임_순번
 ,GAME_SCORE NUMBER --게임_점수
 ,HANDICAP   NUMBER --핸디
 ,WRIGHTER_ID VARCHAR2(100)
 ,WRIGHTER_NM VARCHAR2(100)
 ,WRIGHT_DATE DATE --등록_일자
 ,UPDATE_DATE DATE --수정_일자
);
ALTER TABLE SCORE_MANAGE
ADD CONSTRAINT PK_SCORE_MANAGE PRIMARY KEY(SCORE_ID);

create sequence SCORE_ID_SEQ
start with 1 --1부터 시작
increment by 1 --1씩 증가옵션
nocache;

select SCORE_ID_SEQ.nextval from dual;

SELECT * 
  FROM SCORE_MANAGE

select * from GAME_MANAGE order by WRIGHT_DATE desc;
select * from GAME_MANAGE where GAME_ID=3;

    SELECT RTRIM(LISTAGG(MEM_NAME || ', ') WITHIN GROUP(ORDER BY 1),', ') gameMemList 
      FROM GAME_MEMBER 
     WHERE GAME_ID=3
     GROUP BY GAME_ID

select * from GAME_MANAGE;
select * from SCORE_MANAGE;
select * from GAME_MEMBER;

	SELECT memId,memName,sumScore,avgScore,gameCnt,rownum scoreNo
	  FROM (
			SELECT MEM_ID memId
			      ,MEM_NAME memName
			      ,SUM(GAME_SCORE) sumScore
			      ,ROUND(AVG(GAME_SCORE),2) avgScore
			      ,COUNT(*) gameCnt
			  FROM SCORE_MANAGE
			 GROUP BY MEM_ID,MEM_NAME
			 ORDER BY 4 DESC
	 )

INSERT INTO GAME_MANAGE (GAME_ID,GAME_NM,GAME_CONT,GAME_DTIME,GAME_GB_CD) VALUES ('3','1회차정기모임','2019년1월6일 정모','20190106','01');
COMMIT;


INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('1','3','KDH','김대호');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('2','3','KDS','강대수');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('3','3','KSK','강승구');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('4','3','LSY','이소영');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('5','3','YKD','유경두');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('6','3','JMH','조미해');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('7','3','SMJ','심민재');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('8','3','KSH','김석희');
INSERT INTO GAME_MEMBER (GAME_MEM_ID,GAME_ID,MEM_ID,MEM_NAME) VALUES ('9','3','LJH','이진희');


INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('1','3','KDH','김대호','1팀',194,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('2','3','KDS','강대수','2팀',145,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('3','3','KSK','강승구','3팀',170,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('4','3','LSY','이소영','3팀',163,1,15);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('5','3','YKD','유경두','3팀',129,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('6','3','JMH','조미해','1팀',132,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('7','3','SMJ','심민재','2팀',152,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('8','3','KSH','김석희','2팀',90,1,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('9','3','LJH','이진희','1팀',115,1,15);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('10','3','KDH','김대호','1팀',160,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('11','3','KDS','강대수','2팀',195,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('12','3','KSK','강승구','3팀',169,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('13','3','LSY','이소영','3팀',164,2,15);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('14','3','YKD','유경두','3팀',181,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('15','3','JMH','조미해','1팀',168,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('16','3','SMJ','심민재','2팀',103,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('17','3','KSH','김석희','2팀',100,2,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('18','3','LJH','이진희','1팀',77,2,15);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('19','3','KDH','김대호','1팀',165,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('20','3','KDS','강대수','2팀',178,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('21','3','KSK','강승구','3팀',156,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('22','3','LSY','이소영','3팀',155,3,15);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('23','3','YKD','유경두','3팀',154,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('24','3','JMH','조미해','1팀',124,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('25','3','SMJ','심민재','2팀',123,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('26','3','KSH','김석희','2팀',106,3,0);
INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,TEAM_NM,GAME_SCORE,GAME_SEQ,HANDICAP) VALUES ('27','3','LJH','이진희','1팀',79,3,15);

select * from SCORE_MANAGE;
SELECT ROWNUM rank
       ,TEAM_NM teamNm
       ,MEM_NAME memName
       ,GAME1 game1
       ,GAME2 game2
       ,GAME3 game3
       ,AVG_GAME_SCORE avgGameScore
       ,TOTAL_SCORE totalScore
       ,HANDICAP handicap
  FROM (SELECT *
		 FROM (SELECT TEAM_NM
		      ,MEM_NAME
		      ,SUM(CASE WHEN GAME_SEQ = 1 THEN GAME_SCORE ELSE 0 END) GAME1
		      ,SUM(CASE WHEN GAME_SEQ = 2 THEN GAME_SCORE ELSE 0 END) GAME2
		      ,SUM(CASE WHEN GAME_SEQ = 3 THEN GAME_SCORE ELSE 0 END) GAME3
		      ,ROUND(AVG(GAME_SCORE),1) AVG_GAME_SCORE
		      ,SUM(GAME_SCORE) TOTAL_SCORE
		      ,SUM(CASE WHEN GAME_SEQ = 1 THEN HANDICAP ELSE 0 END) HANDICAP
		  FROM SCORE_MANAGE
		 GROUP BY TEAM_NM,MEM_NAME)
		 ORDER BY AVG_GAME_SCORE DESC);
COMMIT;



insert into GAME_MEMBER (GAME_MEM_ID,                               
GAME_ID,                               
MEM_ID,                              
MEM_NAME)       values
(99,
;
SELECT * FROM GAME_member;
SELECT * FROM GAME_MANAGE;

SELECT * FROM GAME_member where game_id = 7;
5,
'hangun0626',             
'김현우');


     select B.GAME_ID gameId,
            B.GAME_NM gameNm,
            B.GAME_CONT gameCont,
            B.GAME_DTIME gameDtime,
            B.GAME_GB_CD gameGbCd,
            B.CLUB_ID clubId,
            B.WRIGHTER_ID wrighterId,
            B.WRIGHTER_NM wrighterNm,
            B.WRIGHT_DATE wrightDate,
            'hangun0626' memId,
            (select count(*) 
                from GAME_MEMBER A 
               WHERE A.MEM_ID = 'hangun0626'
                 AND A.GAME_ID = B.GAME_ID) attendYn  ,
            UPDATE_DATE updateDate
       from GAME_MANAGE B
      where B.GAME_ID=7;
      
      
    SELECT RTRIM(LISTAGG(MEM_NAME || ', ') WITHIN GROUP(ORDER BY 1),', ') memList
      FROM GAME_MEMBER 
     WHERE GAME_ID=3
     GROUP BY GAME_ID;
     
     select * from GAME_MEMBER where GAME_ID = 7 ;
     delete from GAME_MEMBER where GAME_ID = 7 AND MEM_ID = 'hangun0626';
     
     select * from SCORE_MANAGE;
     INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,GAME_SCORE,GAME_SEQ) VALUES (SCORE_ID_SEQ.nextval, '7', 'hangun0626', '김현우' , '10', '1');
     INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,GAME_SCORE,GAME_SEQ) VALUES (SCORE_ID_SEQ.nextval, '7', 'hangun0626', '김현우', '10', '1');
     INSERT INTO SCORE_MANAGE (SCORE_ID,GAME_ID,MEM_ID,MEM_NAME,GAME_SCORE,GAME_SEQ) VALUES (SCORE_ID_SEQ.nextval, "7", "hangun0626", "김현우" , "10", "1")
     delete from SCORE_MANAGE where GAME_ID = '7';
     
     
	SELECT ROWNUM rank
	       ,TEAM_NM teamNm
	       ,MEM_ID memId
	       ,MEM_NAME memName
	       ,GAME1 game1
	       ,GAME2 game2
	       ,GAME3 game3
	       ,AVG_GAME_SCORE avgGameScore
	       ,TOTAL_SCORE totalScore
	       ,HANDICAP handicap
	  FROM (SELECT *
			 FROM (SELECT A.TEAM_NM
			             ,B.MEM_ID
			             ,B.MEM_NAME
			             ,SUM(CASE WHEN GAME_SEQ = 1 THEN A.GAME_SCORE ELSE 0 END) GAME1
			             ,SUM(CASE WHEN GAME_SEQ = 2 THEN A.GAME_SCORE ELSE 0 END) GAME2
			             ,SUM(CASE WHEN GAME_SEQ = 3 THEN A.GAME_SCORE ELSE 0 END) GAME3
			             ,ROUND(AVG(A.GAME_SCORE),1) AVG_GAME_SCORE
			             ,SUM(A.GAME_SCORE) TOTAL_SCORE
			             ,SUM(CASE WHEN A.GAME_SEQ = 1 THEN A.HANDICAP ELSE 0 END) HANDICAP
			         FROM SCORE_MANAGE A, GAME_MEMBER B
			        WHERE B.GAME_ID = 7
			          AND A.GAME_ID(+) = B.GAME_ID
			          AND A.MEM_ID(+)  = B.MEM_ID
			        GROUP BY A.TEAM_NM,B.MEM_ID,B.MEM_NAME)
			 ORDER BY AVG_GAME_SCORE DESC)
			 
			 SELECT * FROM SCORE_MANAGE;
			 SELECT * FROM GAME_MEMBER;
			 
			 
			       SELECT A.TEAM_NM
			             ,B.MEM_ID
			             ,B.MEM_NAME
			             ,A.GAME_SCORE
			         FROM SCORE_MANAGE A, GAME_MEMBER B
			        WHERE B.GAME_ID = 7
			          AND A.GAME_SEQ = 1
			          AND A.GAME_ID(+) = B.GAME_ID
			          AND A.MEM_ID(+)  = B.MEM_ID
			        ORDER BY A.TEAM_NM,A.GAME_SCORE,B.MEM_NAME;
			        
			        SELECT * FROM SCORE_MANAGE;
			       
			        SELECT MEM_ID,MEM_NAME
			          FROM MEMBER;
			        
	 insert into GAME_MEMBER (GAME_MEM_ID,
	      GAME_ID,
	      MEM_ID,
	      MEM_NAME,
	      WRIGHT_DATE)
     SELECT GAME_MEM_ID_SEQ.nextval,
            '7' as gameId,
            MEM_ID, 
            MEM_NAME ,
            sysdate
       FROM MEMBER 
      WHERE MEM_ID = 'hangun0626'
      
      
     values(GAME_MEM_ID_SEQ.nextval,
            #{gameId},
            #{memId},
            #{memName},
            sysdate)
            
     select * from GAME_MEMBER where game_id = '7'
delete from SCORE_MANAGE where GAME_ID = 7 AND GAME_SEQ = ?;